
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title:  paula bendiek
email: paula.bendiek@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my blog about energy, housing, data & other interesting random stuff. 
baseurl: "pbendiek.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: PBendiek
linkedin_username: paula-bendiek-b40422184
# social_links: 
#   - 
#     platform: linkedin
#       user_url: https://www.linkedin.com/in/paula-bendiek-b40422184

# Build settings
theme: minima
plugins:
  - jekyll-feed

defaults: 
  - 
    scope: 
      path: "" # files to which default applies to 
      type: "posts"
    values: 
        layout: "post"